### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brylie** [codetricity/jenny_tutorial#1]
When sharing code on GitHub, authors sometimes forget to include a LICENSE file describing how people can use the code. 

By default, code without an included LICENSE falls under full Copyright limits, even when shared publicly, meaning people cannot legally use, modify, or redistribute the code without explicit permission from the original author. Every single person who wants to use the software would need to contact the original author to obtain legal permission to use the code.

Adding a LICENSE file will grant all people usage terms from the author. That is why it is essential to add a LICENSE file for open source software that contains license text from one of the common open source licenses, such as MIT.

Please remember to include a LICENSE file in repositories that you share with the intention for people to learn from and build on your work.

- https://choosealicense.com
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by codetricity** [comment]
I don't want to license this project as it is a tutorial and the students should use the code as a reference for concepts to build their own tutorial.  Also, Jenny is updated rapidly.   People should not use this code as is and include it in their projects.  They can use it as a reference for the tutorial.
